export const FETCHED_ABSENCES_SUCCESS = "FETCHED_ABSENCES_SUCCESS";
export const FETCHED_ABSENCES_ERROR = "FETCHED_ABSENCES_ERROR";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const GO_TO_PAGE = "GO_TO_PAGE";
export const ON_FILTER = "ON_FILTER";
export const ON_CONFIRM_REQUEST = "ON_CONFIRM_REQUEST";
export const ON_REJECT_REQUEST = "ON_REJECT_REQUEST";
