export const FETCHED_ABSENCES_SUCCESS = "FETCHED_ABSENCES_SUCCESS";
export const FETCHED_ABSENCES_ERROR = "FETCHED_ABSENCES_ERROR";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const GO_TO_PAGE = "GO_TO_PAGE";
